select * from CLIENTE
SELECT * FROM PEDIDO
SELECT * FROM PEDIDO_ITEM
SELECT * FROM PRODUTO
SELECT * FROM VENDEDOR

/* 01 � Elabore um relat�rio que contenha as seguintes informa��es: cliente, pedido e produto 
al�m do valor comercializado(qtd*vl unit�rio), ordene da seguinte forma: cliente, pedido e produto! */
SELECT CLT.CODIGO_CLIENTE , PDD.CODIGO_PEDIDO,PRO.CODIGO_PRODUTO ,(PDI.QUANTIDADE * PRO.VALOR_UNITARIO) AS valor_comercializado
FROM CLIENTE CLT, PEDIDO PDD, PEDIDO_ITEM PDI, PRODUTO PRO
WHERE CLT.CODIGO_CLIENTE = PDD.CODIGO_CLIENTE
AND PDD.CODIGO_PEDIDO = PDI.CODIGO_PEDIDO
AND PDI.CODIGO_PRODUTO = PRO.CODIGO_PRODUTO
ORDER BY CLT.CODIGO_CLIENTE,PDD.CODIGO_PEDIDO,PRO.CODIGO_PRODUTO

/* 02 � Crie um relat�rio que contenha as seguintes informa��es: quantidades e 
valores(qtd*vl unit�rio) comercializados por cliente e pedido, ordene da seguinte forma: cliente e pedido! */
SELECT CLT.CODIGO_CLIENTE,PDD.CODIGO_PEDIDO,
	COUNT(PDI.QUANTIDADE) AS QTD_COMERCIALIZADA ,
	SUM(PDI.QUANTIDADE * PRO.VALOR_UNITARIO) AS VALOR_COMERCIALIZADO
FROM CLIENTE CLT, PEDIDO PDD, PEDIDO_ITEM PDI, PRODUTO PRO
WHERE CLT.CODIGO_CLIENTE = PDD.CODIGO_CLIENTE
AND PDD.CODIGO_PEDIDO = PDI.CODIGO_PEDIDO
AND PDI.CODIGO_PRODUTO = PRO.CODIGO_PRODUTO
GROUP BY CLT.CODIGO_CLIENTE,PDD.CODIGO_PEDIDO
ORDER BY  CLT.CODIGO_CLIENTE,PDD.CODIGO_PEDIDO;

/* prof 
SELECT    CLI.CODIGO_CLIENTE,PDD.CODIGO_PEDIDO,
	  COUNT(PDI.QUANTIDADE) 			  AS QTD_COMERCIALIZADO,
	  SUM(PDI.QUANTIDADE *PDT.VALOR_UNITARIO)   AS VALOR_COMERCIALIZADO
FROM	  CLIENTE CLI, PEDIDO PDD, PEDIDO_ITEM PDI, PRODUTO PDT
WHERE	  CLI.CODIGO_CLIENTE = PDD.CODIGO_CLIENTE
AND	  PDD.CODIGO_PEDIDO = PDI.CODIGO_PEDIDO
AND	  PDI.CODIGO_PRODUTO = PDT.CODIGO_PRODUTO
GROUP BY  CLI.CODIGO_CLIENTE,PDD.CODIGO_PEDIDO
ORDER BY  CLI.CODIGO_CLIENTE,PDD.CODIGO_PEDIDO;
*/

/* 03 Crie um relat�rio que contenha as seguintes informa��es: quantidades e 
valores(qtd*vl unit�rio) comercializados por cliente, ordene da seguinte forma: cliente e pedido! */

SELECT CLT.CODIGO_CLIENTE,
	COUNT(PDI.QUANTIDADE) AS QTD_COMERCIALIZADA ,
	SUM(PDI.QUANTIDADE * PRO.VALOR_UNITARIO) AS VALOR_COMERCIALIZADO
FROM CLIENTE CLT, PEDIDO PDD, PEDIDO_ITEM PDI, PRODUTO PRO
WHERE CLT.CODIGO_CLIENTE = PDD.CODIGO_CLIENTE
AND PDD.CODIGO_PEDIDO = PDI.CODIGO_PEDIDO
AND PDI.CODIGO_PRODUTO = PRO.CODIGO_PRODUTO
GROUP BY CLT.CODIGO_CLIENTE
ORDER BY  CLT.CODIGO_CLIENTE

/* PROF

SELECT   CLI.CODIGO_CLIENTE,
	 COUNT(PDI.QUANTIDADE)			 AS QTD_COMERCIALIZADO,
	 SUM(PDI.QUANTIDADE *PDT.VALOR_UNITARIO) AS VALOR_COMERCIALIZADO
FROM	 CLIENTE CLI, PEDIDO PDD, PEDIDO_ITEM PDI, PRODUTO PDT
WHERE	 CLI.CODIGO_CLIENTE = PDD.CODIGO_CLIENTE
AND	 PDD.CODIGO_PEDIDO = PDI.CODIGO_PEDIDO
AND	 PDI.CODIGO_PRODUTO = PDT.CODIGO_PRODUTO
GROUP BY CLI.CODIGO_CLIENTE
ORDER BY CLI.CODIGO_CLIENTE;
*/

/* 04 � Mostre os totais comercializados, quantidades e valores(qtd*vl unit�rio)! */

SELECT 
	COUNT(PDI.QUANTIDADE) AS QTD_COMERCIALIZADA ,
	SUM(PDI.QUANTIDADE * PRO.VALOR_UNITARIO) AS VALOR_COMERCIALIZADO
FROM CLIENTE CLT, PEDIDO PDD, PEDIDO_ITEM PDI, PRODUTO PRO
WHERE CLT.CODIGO_CLIENTE = PDD.CODIGO_CLIENTE
AND PDD.CODIGO_PEDIDO = PDI.CODIGO_PEDIDO
AND PDI.CODIGO_PRODUTO = PRO.CODIGO_PRODUTO

/* PROF 
SELECT 
	COUNT(PDI.QUANTIDADE)			    AS QTD_COMERCIALIZADO,
	SUM(PDI.QUANTIDADE *PDT.VALOR_UNITARIO) AS VALOR_COMERCIALIZADO
FROM	CLIENTE CLI, PEDIDO PDD, PEDIDO_ITEM PDI, PRODUTO PDT
WHERE	CLI.CODIGO_CLIENTE = PDD.CODIGO_CLIENTE
AND	PDD.CODIGO_PEDIDO = PDI.CODIGO_PEDIDO
AND	PDI.CODIGO_PRODUTO = PDT.CODIGO_PRODUTO;
*/

/* 5 Elabore um relat�rio que contenha as seguintes informa��es: cliente, pedido
e produto al�m do valor comercializado(qtd*vl unit�rio), ordene da seguinte forma: 
cliente, pedido e produto! � Aten��o reescreva a sintaxe SQL utilizando o JOIN que for conveniente!
(INNER, RIGHT, LEFT ou FULL OUTER)!!! */

/* NORMAL */

SELECT CLT.CODIGO_CLIENTE , PDD.CODIGO_PEDIDO,PRO.CODIGO_PRODUTO ,(PDI.QUANTIDADE * PRO.VALOR_UNITARIO) AS valor_comercializado
FROM CLIENTE CLT, PEDIDO PDD, PEDIDO_ITEM PDI, PRODUTO PRO
WHERE CLT.CODIGO_CLIENTE = PDD.CODIGO_CLIENTE
AND PDD.CODIGO_PEDIDO = PDI.CODIGO_PEDIDO
AND PDI.CODIGO_PRODUTO = PRO.CODIGO_PRODUTO
ORDER BY CLT.CODIGO_CLIENTE,PDD.CODIGO_PEDIDO,PRO.CODIGO_PRODUTO

/* COM JOINS */

SELECT CLT.CODIGO_CLIENTE , PDD.CODIGO_PEDIDO,PRO.CODIGO_PRODUTO ,(PDI.QUANTIDADE * PRO.VALOR_UNITARIO) AS valor_comercializado
FROM PEDIDO PDD
INNER JOIN CLIENTE CLT ON PDD.CODIGO_CLIENTE = CLT.CODIGO_CLIENTE
INNER JOIN PEDIDO_ITEM PDI ON PDD.CODIGO_PEDIDO = PDI.CODIGO_PEDIDO
INNER JOIN PRODUTO PRO ON PDI.CODIGO_PRODUTO = PRO.CODIGO_PRODUTO
ORDER BY CLT.CODIGO_CLIENTE,PDD.CODIGO_PEDIDO,PRO.CODIGO_PRODUTO

/* PROF 

SELECT	        CLI.CODIGO_CLIENTE,PDD.CODIGO_PEDIDO,PDT.CODIGO_PRODUTO,
		(PDI.QUANTIDADE *PDT.VALOR_UNITARIO) AS VALOR_COMERCIALIZADO
FROM		PEDIDO PDD
INNER JOIN	CLIENTE CLI      ON CLI.CODIGO_CLIENTE  = PDD.CODIGO_CLIENTE
INNER JOIN	VENDEDOR VDD     ON VDD.CODIGO_VENDEDOR = PDD.CODIGO_VENDEDOR
INNER JOIN	PEDIDO_ITEM PDI  ON PDI.CODIGO_PEDIDO   = PDD.CODIGO_PEDIDO
INNER JOIN	PRODUTOPDT       ON PDT.CODIGO_PRODUTO  = PDI.CODIGO_PRODUTO
ORDER BY	CLI.CODIGO_CLIENTE,PDD.CODIGO_PEDIDO,PDT.CODIGO_PRODUTO;

*/

/* 6 Mostre os clientes cadastrados que podem ter transacionado ou n�o? */

SELECT CLT.CODIGO_CLIENTE, COUNT(PDD.CODIGO_PEDIDO) AS QTD_TRANSACIONADA 
FROM PEDIDO PDD
FULL JOIN CLIENTE CLT ON CLT.CODIGO_CLIENTE = PDD.CODIGO_CLIENTE
GROUP BY CLT.CODIGO_CLIENTE
ORDER BY CLT.CODIGO_CLIENTE

/* PROF

SELECT  CLI.CODIGO_CLIENTE,
  	COUNT(PDD.CODIGO_PEDIDO) AS QTD_COMERCIALIZADO
FROM  	CLIENTE CLI
FULL JOIN PEDIDO PDD
ON	  CLI.CODIGO_CLIENTE = PDD.CODIGO_CLIENTE
GROUP BY  CLI.CODIGO_CLIENTE
ORDER BY  CLI.CODIGO_CLIENTE;
*/

/* 07 � Mostre os cliente que transacionaram? */

SELECT CLT.CODIGO_CLIENTE, COUNT(PDD.CODIGO_PEDIDO) AS QTD_TRANSACIONADA 
FROM PEDIDO PDD
INNER JOIN CLIENTE CLT ON CLT.CODIGO_CLIENTE = PDD.CODIGO_CLIENTE
GROUP BY CLT.CODIGO_CLIENTE 
ORDER BY CLT.CODIGO_CLIENTE

/* PROF
SELECT 	CLI.CODIGO_CLIENTE,
  	COUNT(PDD.CODIGO_PEDIDO) AS QTD_COMERCIALIZADO
FROM  	CLIENTE CLI
INNER JOIN PEDIDO PDD
ON	   CLI.CODIGO_CLIENTE = PDD.CODIGO_CLIENTE
GROUP BY   CLI.CODIGO_CLIENTE
ORDER BY   CLI.CODIGO_CLIENTE;

*/

/* 08 � Mostre os cliente que n�o transacionaram? */

SELECT CLT.CODIGO_CLIENTE, COUNT(PDD.CODIGO_PEDIDO) AS QTD_TRANSACIONADA 
FROM PEDIDO PDD
FULL JOIN CLIENTE CLT ON CLT.CODIGO_CLIENTE = PDD.CODIGO_CLIENTE
WHERE PDD.CODIGO_PEDIDO IS NULL
GROUP BY CLT.CODIGO_CLIENTE 
ORDER BY CLT.CODIGO_CLIENTE

/* PROF

SELECT  CLI.CODIGO_CLIENTE,
  	COUNT(PDD.CODIGO_PEDIDO) AS QTD_COMERCIALIZADO
FROM  	CLIENTE CLI
FULL JOIN PEDIDO PDD
ON	  CLI.CODIGO_CLIENTE = PDD.CODIGO_CLIENTE
WHERE	  CLI.CODIGO_CLIENTE IS NULL
OR	  PDD.CODIGO_CLIENTE IS NULL
GROUP BY  CLI.CODIGO_CLIENTE
ORDER BY  CLI.CODIGO_CLIENTE;

*/


